projects/sandbox/config/routes.rb
Sandbox::Application.routes.draw do
  devise_for :users
  
  devise_scope :user do
    get 'register', to: 'devise/registrations#new', as: :register
    get 'login', to: 'devise/sessions#new', as: :login
    get 'logout', to: 'devise/sessions#destroy', as: :logout
  end

  resources :employees
  get 'feed', to: 'employees#index', as: :feed
  
  get "welcome/index"

  root to: 'employees#index'

  

end

projects/sandbox/app/models/employee.rb
class Employee < ActiveRecord::Base
	attr_accessible :user_id, :sign_up, :firstname, :lastname, :salary, :documents, :sickdays
	
	belongs_to :user
	
end

projects/sandbox/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


attr_accessible :email, :password, :password_confirmation, :remember_me,
                 :first_name, :last_name, :profile_name

has_many :employees

	def full_name 
		first_name + " " + last_name
	end

end

projects/sandbox/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.


    protect_from_forgery with: :exception


before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :first_name
    devise_parameter_sanitizer.for(:sign_up) << :last_name
    devise_parameter_sanitizer.for(:sign_up) << :profile_name
  end

end

projects/sandbox/app/controllers/employees_controller.rb
  class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all

  end

  # GET /employees/1
  # GET /employees/1.json
  def show
    
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render action: 'show', status: :created, location: @employee }
      else
        format.html { render action: 'new' }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:firstname, :lastname, :vacation, :startdate, :type, :manager, :salary, :sickdays, :documents)
    end
end

projects/sandbox/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

projects/sandbox/app/helpers/application_helper.rb
module ApplicationHelper
	def flash_class(type)
		case type 
		when :alert
			"alert-error"
		when :notice
			"alert-success"
		else
			""
		end
	end
end
 

projects/sandbox/app/helpers/employees_helper.rb
module EmployeesHelper
end

projects/sandbox/app/helpers/welcome_helper.rb
module WelcomeHelper
end

projects/sandbox/app/views/employees/_form.html.erb
<%= simple_form_for(@employee, html: {class: "form-horizontal"}) do |f| %>

  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <%= f.input :user_id, collection: User.all, label_method: :full_name%>

  <div class="field">
    <%= f.input :firstname %>
  </div>
  <div class="field">
    
    <%= f.input :lastname %>
  </div>
  <div class="field">
    <%= f.input :vacation %>
  </div>
  <div class="field">
    <%= f.input  :startdate %>
  </div>
  <div class="field">
    <%= f.input :manager %>
  </div>
  <div class="field">
    <%= f.input :salary %>
  </div>
  <div class="field">
    <%= f.input :sickdays %>
  </div>
  <div class="field">
    <%= f.input :documents %>
  </div>
  <div class="form-actions">
    <%= f.button :submit %>

  </div>
<% end %>

projects/sandbox/app/views/employees/edit.html.erb
<h1>Editing employee</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

projects/sandbox/app/views/employees/index.html.erb
<div class = "page-header">
  <h1> All of your employees</h1>
</div>
<h1>Listing employees</h1>

<%= link_to "Add a new employee", new_employee_path, class: "btn btn-success " %>
<% @employees.each do |employee| %>
  <div class="employee">
    <strong><%=employee.firstname %></strong>
      <p><%=employee.startdate %></p>
        <div class = "meta">
          <%= link_to "Show", employee %>
          <span class = "admin">
            <%=link_to "Edit", edit_employee_path(employee)%>
            <%=link_to "Delete", employee, method: :delete, data:{ confirm: "Are you sure?" } %>
          </span>
        </div>
  </div>    
<%end%>

projects/sandbox/app/views/employees/new.html.erb
<h1>New employee</h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

projects/sandbox/app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  
  <b>Manager:</b>
  <%= @employee.user.first_name  %> 
<p>

  <strong>Firstname:</strong>
  <%= @employee.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @employee.lastname %>
</p>

<p>
  <strong>Vacation:</strong>
  <%= @employee.vacation %>
</p>

<p>
  <strong>Startdate:</strong>
  <%= @employee.startdate %>
</p>


<p>
  <strong>Manager:</strong>
  <%= @employee.manager %>
</p>

<p>
  <strong>Salary:</strong>
  <%= @employee.salary %>
</p>

<p>
  <strong>Sickdays:</strong>
  <%= @employee.sickdays %>
</p>

<p>
  <strong>Documents:</strong>
  <%= @employee.documents %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>

projects/sandbox/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sandbox</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
   <!-- <meta name="viewport" content="width=device-width"> -->
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.min.css">
   
</head>
<body>
<ul>
	        	<% if user_signed_in? %>
	        	<li><%= link_to current_user.full_name,edit_user_registration_path%></li>
	        	<li><%= link_to "Log Out", logout_path %></li>
	        
	        	<% else %>
	        	<li><%= link_to "Register", register_path %></li>
	        	<li><%= link_to "Log in", login_path %>
	        	<%end%>
</ul>

	<div class="container-fluid">
		<% flash.each do |type, message| %>
		<div class = "alert <%= flash_class type%>">
			<button class = "close" data-dismiss="alert">x</button>
			<%= message %>
		</div>	
		<% end %>

	</div>
	
	



<div class="container">
      <div class="row-fluid">
    	<div class="span2">
    		<div class="sidebar">
	        <ul class="nav nav-list bs-docs-sidenav affix-top">
	          <li>
	            <a href="#buttonDropdowns"><i class="icon-chevron-right"></i> Home</a>
	          </li>
	          <li>
	            <a href="Hiring.html"><i class="icon-chevron-right"></i> Hiring</a>
	          </li>
	          <li class="active">
	            <a href="OnBoarding.html"><i class="icon-chevron-right"></i> OnBoarding</a>
	          </li>
	          <li>
	            <a href="Manage.html"><i class="icon-chevron-right"></i> Manage Employee</a>
	          </li>
	          <li>
	            <a href="Terminate.html"><i class="icon-chevron-right"></i> Terminate Employee</a>
	          </li>
	        </ul>

     		</div>
     	</div>
     
     

<div class="span10">
      
    <div class="container">
		<%= yield %>
	</div>
	</div>
</div>
</body>
</html>

projects/sandbox/app/views/welcome/index.html.erb
<h1>WHATUP! Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>